[package]
name = "godevnight"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.13.0"
rayon = "~1.10.0"
rand = "0.9.0-alpha.1"
log = "0.4.22"
env_logger = "0.11.3"